### PR TITLE
add dispose method and tabbed view

### PR DESCRIPTION
**Pull request by j4qfrost**
I added the tabbed view to test out disposing the video buffer. The player doesn't seem to have the same memory leak issues as in the golang video_player_plugin, but for some reason my cpu usage spikes up. To reproduce, click back and forth from tab to tab.

### CODE REVIEW

**Comment by dvc94ch** [comment]
dropping the VideoStream should exit the video thread and dropping the player should exit the decoder thread.

**Comment by j4qfrost** [comment]
Are those suggestions or how it currently works? I'm having a little trouble dropping the Player object. I expected removing it from the channels registry was enough, but the thread lives on.

**Comment by j4qfrost** [comment]
The culprit is the audio stream. The video stream behaves how you describe it. I'll take a look in a bit.

**Comment by j4qfrost** [comment]
Ignore my last comment about the audio. I added some checks to exit the threads.

**Pull request closed without merging**
